### PR TITLE
fixes #455 incorrect error msg bug

### LINKED ISSUE #455: deleting a person from a group results in incorrect error message
A few weeks ago I created a second Tam account on Rorganize & joined the cornz just to double check that 'a person has joined your group' emails were getting sent out. Today I deleted that Tam from rorganize, and upon doing so, I was redirected to /groups with the error message 'you have left your group, please consider buying everyone cake on your last day' or whatever is it. (I double checked and I definitely removed the correct Tam and I am still a member of rubycorns). 

So.... that's a bug.

### PR DESCRIPTION
**Pull request by berlintam**

### CODE REVIEW

File: app/controllers/memberships_controller.rb [hunk 1]
```diff
@@ -15,16 +15,21 @@ def create
...
+
     flash[:success] = leave_message
     redirect_to groups_path
   end
 
   private
 
   def leave_message
-    "You have left your group. No doubt they will miss you." +
+    if @membership.person_id == current_person.id
```
Comment (til) [inline app/controllers/memberships_controller.rb]: It should be possible to compare the actual persons with each other whether they are equal, instead of their ids. In general, I'd say dealing with the actual object is preferred in ruby, over using ids or other "technical details".

File: spec/controllers/memberships_controller_spec.rb [hunk 2]
```diff
@@ -42,25 +41,47 @@
...
   describe 'destroy' do
 
-    before do
-      person.join!(group)
-      @membership = person.memberships.first
-    end
+    context 'removing yourself from a group' do
+      before do
+        person.join!(group)
+        @membership = person.memberships.first
```
Comment (til) [inline spec/controllers/memberships_controller_spec.rb]: I know, it was like this before, but if you are interested in improving this spec, you might want to consider using a `let` thingy here instead of an instance variable. I don't think there is any specific reason why an instance variable would be needed, and it's more common to use `let` within rspec.

Comment (berlintam) [inline spec/controllers/memberships_controller_spec.rb]: 👍

File: app/controllers/memberships_controller.rb (hunk 1 above)
Comment (berlintam) [inline app/controllers/memberships_controller.rb]: ah, cool! will do!

**Comment by PragTob** [comment]
Something moving forward here? :)

**Comment by berlintam** [comment]
oh gawd I forgot about it.

**Comment by PragTob** [comment]
sobbing

**Comment by berlintam** [comment]
sorry

**Comment by PragTob** [comment]
did i miss it

**Comment by berlintam** [comment]
here you go @PragTob. sorry this took so long!
sorry

**Comment by PragTob** [comment]
No worries, thanks a lot!

thanks
